USE ewma;

INSERT INTO department (abbr, display) VALUES
    ('zoo', 'Electrical, Computer, and Software Engineering'),
    ('chem', 'Chemical Engineering'),
    ('special', 'Biomedical Engineering, Energy and Environment Engineering'),
    ('mech', 'Mechanical Engineering'),
    ('civil', 'Civil Engineering'),
    ('alum', 'Engineering Alumni'),
    ('geo', 'Geomatics Engineering');

INSERT INTO movies (title, rating, year, id, dept, src, mime, theme) VALUES
    ('Fifteen Minutes', NULL, 1991, 1, NULL, 'RPpzzmyw45c.webm', 'video/webm', NULL),
    ('Mechsico', NULL, 1991, 2, 'mech', 'ljkdi0fvFuo.webm', 'video/webm', 'Mexico'),
    ('Zoo Music', 20, 1991, 3, 'zoo', '1U10cOPGQNA.webm', 'video/webm', 'Much Music'),
    ('Star Trek', NULL, 1995, 4, 'geo', 'K4R2E31COhk.webm', 'video/webm', 'Star Trek'),
    ('Mech Files', NULL, 1996, 5, 'mech', 'IxipPYdKixI.webm', 'video/webm', 'X Files'),
    ('X Files', NULL, 1996, 6, 'zoo', 'FOYy5Cc1-xg.webm', 'video/webm', 'X Files'),
    ('In Search of the Zooids', 35, 1997, 7, 'zoo', 'hRqlvYdkM9o.webm', 'video/webm', 'Star Wars'),
    (NULL, NULL, 1999, 8, 'chem', 'iUQRrTji6kU.webm', 'video/webm', NULL),
    ('Zooro', NULL, 1999, 9, 'zoo', 'CEk9bDVYEE0.webm', 'video/webm', 'Zorro'),
    ('Chem-Hur', 15, 2000, 10, 'chem', 'Gl40jdYPXGw.webm', 'video/webm', NULL),
    ('Horror Movie', NULL, 2000, 11, 'mech', 'rxO0V2REFRw.webm', 'video/webm', NULL),
    ('Zookes of Hazzard', NULL, 2001, 12, 'zoo', 'fzi-YTHw0lA.webm', 'video/webm', 'Dukes of Hazard'),
    (NULL, NULL, 2002, 13, 'civil', 'KGQfCxp7mk4.webm', 'video/webm', NULL),
    ("Wayne's World", NULL, 2002, 14, 'civil', NULL, NULL, NULL),
    ('Geolympics', NULL, 2002, 15, 'geo', 'wJ_avugYrBI.webm', 'video/webm', 'Olympics'),
    ('Mechsmen', NULL, 2002, 16, 'mech', 'h_MOj43rYhs.webm', 'video/webm', 'X-Men'),
    ('00Zoo', NULL, 2002, 17, 'zoo', 'dLzdo7_tkS8.webm', 'video/webm', 'James Bond'),
    ('Chemadian', NULL, 2003, 18, 'chem', 'a8KUjvNdfX0.webm', 'video/webm', NULL),
    ('The Civpranos', NULL, 2003, 19, 'civil', 'kEmVSFmDZds.webm', 'video/webm', 'The Sopranos'),
    ('Austenite Powers', NULL, 2003, 20, 'mech', 'imaaNtk2ito.webm', 'video/webm', 'Austin Powers'),
    ('Kung ZOO', NULL, 2003, 21, 'zoo', 'h3Td-sCLmPA.webm', 'video/webm', NULL),
    ('Geostbusters', NULL, 2003, 22, 'geo', NULL, NULL, 'Ghostbusters'),
    ('The Republic Strikes Back', NULL, 2004, 23, 'civil', 's8DE8lVq1no.webm', 'video/webm', 'Star Wars'),
    ('MarGeo Bros', NULL, 2004, 24, 'geo', 'Itv5n7G_szo.webm', 'video/webm', 'Nintendo'),
    ('Made in Mechsico', NULL, 2004, 25, 'mech', 'p_0XPhqFDPY.webm', 'video/webm', 'Mexico'),
    ('ZooBar', NULL, 2004, 26, 'zoo', '3mXrzqcFoR0.mp4', 'video/mp4', 'Fubar'),
    ('Zooper Heroes', NULL, 2005, 27, 'zoo', '_LdXD1i7qt8.webm', 'video/webm', 'Super Heroes'),
    ('TScheM', NULL, 2006, 28, 'chem', '0on_TeHOHXY.webm', 'video/webm', NULL),
    ('Ceuslander', NULL, 2006, 29, 'civil', 'UR1KAPe_Ywk.webm', 'video/webm', 'Zoolander'),
    ('Mechopoly', NULL, 2006, 30, 'mech', 'gOkxiVYt3us.webm', 'video/webm', 'Monopoly'),
    ('Monty Pithon', NULL, 2006, 31, 'zoo', '0Edqtw4aqHQ.webm', 'video/webm', 'Monty Python'),
    ('Bio-Witch Project', NULL, 2006, 32, 'special', 'Nw_UCNnBQEE.webm', 'video/webm', "Blair Witch Project"),
    ('Cessame Street', NULL, 2007, 33, 'chem', 'rbTKKzJnk3I.webm', 'video/webm', 'Sesame Street'),
    ('The Good, The Bad, & The Civil', NULL, 2007, 34, 'civil', 'WMJ7Mzn1hoU.webm', 'video/webm', 'The Good, The Bad, and The Ugly'),
    ('Mechscalibur', NULL, 2007, 35, 'mech', 'Pdj6DCwQnRU.webm', 'video/webm', 'Excalibur'),
    ('Star Wars: Episode ZOO', NULL, 2007, 36, 'zoo', 'jrwniGtr_IE.webm', 'video/webm', 'Star Wars'),
    ("Wayne's Geoid", NULL, 2008, 37, 'geo', 'ZyYG1WCO3P0.webm', 'video/webm', "Wayne's World"),
    ('Batmanu: The Mech Knight (Part 1 of 4)', NULL, 2009, 38, 'mech', 'OUuicbigCNg.webm', 'video/webm', 'Batman'),
    ('Batmanu: The Mech Knight (Part 2 of 4)', NULL, 2009, 39, 'mech', 'td7UfKVrFq4.webm', 'video/webm', 'Batman'),
    ('Batmanu: The Mech Knight (Part 3 of 4)', NULL, 2009, 40, 'mech', 'B11yvnhz8RQ.webm', 'video/webm', 'Batman'),
    ('Batmanu: The Mech Knight (Part 4 of 4)', NULL, 2009, 41, 'mech', 'lC_kQE5-E_w.webm', 'video/webm', 'Batman'),
    ('The Geodfather', NULL, 2009, 42, 'geo', 'CQYnXpLUun8.mp4', 'video/mp4', 'The Godfather'),
    ('Matrix Zooloaded', NULL, 2009, 43, 'zoo', 'EDPJcflSEx0.mp4', 'video/mp4', 'The Matrix'),
    ('Geostice League', NULL, 2010, 44, 'geo', 'YjF2Uih4Xc8.webm', 'video/webm', 'Superheroes'),
    ('Spark Trek', 84, 2010, 45, 'zoo', 'Nln_GjqVQUU.mp4', 'video/mp4', 'Star Trek'),
    ('Combustamove', NULL, 2010, 46, 'chem', 'bASE_GJJsgg.mp4', 'video/mp4', NULL),
    ('Civil Night Live', NULL, 2010, 47, 'civil', 'ki32OcbaHgU.mp4', 'video/mp4', 'Saturday Night Live'),
    ('Mechiana Jones', NULL, 2010, 48, 'mech', 'ho1oeB0IbPw.mp4', 'video/mp4', 'Indiana Jones'),
    ('Left for Biomed', NULL, 2010, 49, 'special', '3QSRpo3qdLE.mp4', 'video/mp4', 'Zombies'),
    ('The Geoffice', NULL, 2011, 50, 'geo', 'zkaCfesHFkE.webm', 'video/webm', 'The Office'),
    ('CSI ZOO York', NULL, 2011, 51, 'zoo', 'MbuoVgC_Gv4.mp4', 'video/mp4', 'CSI'),
    ('Geo Presents the 90s (Audio Commentary)', NULL, 2012, 52, 'geo', 'AfsHBHT0Mno.mp4', 'video/mp4', NULL),
    ('Geo Presents the 90s', NULL, 2012, 53, 'geo', 'IKfQgJ8CAvI.mp4', 'video/mp4', NULL),
    ('Pokemon: ZOO Version', NULL, 2012, 54, 'zoo', 'OxTxx9HpZeg.mp4', 'video/mp4', 'Pokemon'),
    ('GeoldenEye', 95, 2013, 55, 'geo', 'I17EdiA8kVs.mp4', 'video/mp4', 'James Bond'),
    ('Mechtendo', 83, 2013, 56, 'mech', 'amPyT5W6y9M.webm', 'video/webm', 'Nintendo'),
    ('Scooby Zoo, Where Are You!', 90, 2013, 57, 'zoo', 'yfEue8SKwkk.mp4', 'video/mp4', 'Scooby Doo'),
    ('Civil Sucks', NULL, 2013, 58, 'civil', NULL, NULL, NULL),
    ('Mechsmas Miracle', NULL, 2014, 59, 'mech', 'jB9H2Vo1c6k.mp4', 'video/mp4', NULL),
    ('Geotroopers', NULL, 2014, 60, 'geo', 'Kqggx8jC30g.mp4', 'video/mp4', 'Super Troopers'),
    ('Goldchember', NULL, '2014', 61, 'chem', 'sl9fvhXwFqk.mp4', 'video/mp4', 'James Bond'),
    ('Game of Gears', 23, 2014, 62, 'alum', 'BY0ZETx3Kbg.mp4', 'video/mp4', 'Game of Thrones'),
    ('Dora the Specialized Explorer', NULL, 2014, 63, 'special', '00VdTaj6Wes.mp4', 'video/mp4', 'Dora the Explorer'),
    ('Back to the Zooture', 40, 2014, 64, 'zoo', 'b2JKT1g2enc.mp4', 'video/mp4', 'Back to the Future'),
    ('Despicivil Me', NULL, 2014, 65, 'civil', NULL, NULL, 'Descipable Me'),
    ('The Zooperheroes', NULL, 2015, 66, 'zoo', 'FurX5HFrUmc.mp4', 'video/mp4', 'Superheroes'),
    ('Chemi-Pro', NULL, 2015, 67, 'chem', NULL, NULL, 'Semi-Pro'),
    ('21 F Block', NULL, 2015, 68, 'civil', NULL, NULL, '21 Jump Street'),
    ('SpongeBob MechPants', 70, 2015, 69, 'mech', 'BeDEdIO3wtY.mp4', 'video/mp4', 'Spongebob'),
    ('Geoscars', NULL, 2015, 70, 'geo', 'SzJsMG1PUEE.mp4', 'video/mp4', 'The Oscars'),
    ('Survivor: Special Edition', NULL, 2015, 71, 'special', NULL, NULL, 'Survivor'),
    ('Lord of the Iron Rings, the Fellowship of Zoo', 93, 2016, 72, 'zoo', 'sUuysEWQ8AM.mp4', 'video/mp4', 'Lord of the Rings'),
    ('Americhem Pie', NULL, 2016, 73, 'chem', NULL, NULL, 'American Pie'),
    ('Alice in Civil Land', 65, 2016, 74, 'civil', 'dsMpjUKQ8FA.mp4', 'video/mp4', 'Alice in Wonderland'),
    ("Sch'mech'", NULL, 2016, 75, 'mech', 'fVgcmwHw3Xs.mp4', 'video/mp4', 'Shrek'),
    ('2001 a Space Geodessey', NULL, 2016, 76, 'geo', NULL, NULL, '2001: a Space Odessey'),
    ('Special School Bus', NULL, 2016, 77, 'special', NULL, NULL, 'The Magic School Bus'),
    ('The Chemzard of Oz', NULL, 2017, 78, 'chem', 'QVDbaEq-VeI.mp4', 'video/mp4', 'The Wizard of Oz'),
    ('Empire State of Zoo', NULL, 2017, 79, 'zoo', 'o8Huxi80_LI.mp4', 'video/mp4', 'Star Wars'),
    ('Puss In Steel Toed Boots', NULL, 2017, 80, 'civil', 'aTlyb1plQXc.mp4', 'video/mp4', 'Puss in Boots'),
    ('Texas Chainsaw Messacre', NULL, 2017, 81, 'mech', 'armv5xZj6C8.mp4', 'video/mp4', 'Texas Chainsaw Massacre'),
    ('Average Geos', NULL, 2017, 82, 'geo', 'TSlVrMTDs_I.mp4', 'video/mp4', 'Average Joes'),
    ('Saving Private Special', 50, 2017, 83, 'special', 'BqdtfGVVI5k.mp4', 'video/mp4', 'Saving Private Ryan'),
    ('OChems 11', NULL, 2013, 84, 'chem', NULL, NULL, "Ocean's Eleven"),
    ('Breakchem Bad', NULL, 2012, 85, 'chem', NULL, NULL, 'Breaking Bad'),
    ('Chemception', NULL, 2011, 86, 'chem', NULL, NULL, 'Inception'),
    ('Civsons', 10, 1991, 87, 'civil', '9mU_Evzfcl8.webm', 'video/webm', 'The Simpsons'),
    ('Plumbob Squarepants', NULL, 2006, 88, 'geo', 'WtJSwRUR-JM.mp4', 'video/mp4', 'Spongebob'),
    ('300', NULL, 2008, 89, 'zoo', 'pGjcb-BrxRE.mp4', 'video/mp4', '300'),
    ('Nightmare on Chem street', NULL, 2004, 90, 'chem', NULL, NULL, 'Nightmare on Elm Street');

INSERT INTO award (name, id, movie_id, note) VALUES
    ("Most Improved", 1, 78, NULL),
    ("Viewer's Choice", 2, 79, NULL),
    ("Special Effects", 3, 79, NULL),
    ("Best Prof Cameo", 4, 79, "Norm Bartley"),
    ("Best Actor", 5, 82, "Nathan Patton, Peter LeFleur"),
    ("Best Actress", 6, 81, "Reanna Sawatzky, Syliva"),
    ("Best Meme", 7, 81, "Toboghini"),
    ("Best 4th Wall Break", 8, 82, "Script"),
    ("Best Judge Cameo", 9, 81, "Toboghini"),
    ("Best Hydration Cue", 10, 79, "Ackbar"),
    ("Best Song/Dance", 11, 79, "Empire State of ZOO"),
    ("Sexxxy Award", 12, 81, NULL),
    ("Best Chase Scene", 13, 81, NULL),
    ("Best WTF Moment", 14, 81, "Nipple"),
    ("Best Department Diss", 15, 81, "Civil Project Management"),
    ("Best Fight Scene", 16, 79, "Ilbe Wet vs Vader"),
    ("Best Crotch Shot", 17, 80, "Guns"),
    ("Best Speech", 18, 83, NULL),
    ("Best Pun", 19, 81, "Breadboard"),
    ("Best Plot Twist", 20, 82, "Still lost"),
    ("Best WTF Moment", 21, 75, "Making out"),
    ("Viewer's Choice", 22, 75, NULL),
    ("Plot Twist", 23, 75, "Gender change"),
    ("Special Effects", 24, 72, NULL),
    ("Best John Cena", 25, 76, NULL),
    ("Best Diss", 26, 76, "Girl?"),
    ("Best Chase Scene", 27, 76, "Girl?"),
    ("Best Sexxxy Scene", 28, 74, NULL),
    ("Best Actor", 29, 72, "Troy Brintnell, Smaegol"),
    ("Best Actress", 30, 72, "Miriam Dietz, Gandalf the Small"),
    ("Best Hydration Queue", 31, 72, "One Does Not Simply"),
    ("Best WTF Moment", 32, 59, NULL),
    ("Balls of Steel", 33, 59, NULL),
    ("Best Judge Cameo", 34, 59, NULL),
    ("Special Effects", 35, 59, NULL),
    ("Best Hydration Cue", 36, 55, "Kill Counter"),
    ("Special Effects", 37, 55, NULL),
    ("Best Actor", 38, 55, NULL),
    ("Viewer's Choice", 39, 55, NULL),
    ("Best Dance Scene", 40, 56, NULL),
    ("Best Chase", 41, 56, NULL),
    ("Best Slow Mo", 42, 56, NULL),
    ("Best Original Music", 43, 53, NULL),
    ("Best Dance", 44, 53, NULL),
    ("Best Villains", 45, 53, NULL),
    ("Best Nostalgic Moment", 46, 53, NULL),
    ("Best Actress", 47, 53, NULL),
    ("Viewer's Choice", 48, 53, NULL),
    ("Best Hydration Cue", 49, 50, NULL),
    ("Best Actor", 50, 50, NULL),
    ("Viewer's Choice", 51, 50, NULL),
    ("Best Dance Scene", 52, 77, NULL),
    ("Best Fight Scene", 53, 70, NULL),
    ("Best Picture", 54, 54, NULL),
    ("Best Special Effects", 55, 54, NULL),
    ("Best Action Scene", 56, 54, NULL),
    ("Best Sexxxy Scene", 57, 54, NULL),
    ("Best Cross Dressing", 58, 54, NULL),
    ("Best Commercial", 59, 54, NULL),
    ("Best Picture", 60, 51, NULL);
